# ===================================
# LEON CONFIG
# ===================================

MARKET = "Gold_Spot"

TIMEFRAME_MAIN = "M15"
TIMEFRAME_CONTEXT = "H4"
TIMEFRAME_BIAS = "D1"

MAX_TRADES_DAY = 0

MIN_SETUP_SCORE = 90

TELEGRAM_ENABLED = False

SHADOW_TRADE_ENABLED = True

JOURNAL_ENABLED = True

MEMORY_CONTEXT_ENABLED = True

MEMORY_SHADOW_MODE = True

VERSION = "0.2"
